"""
=============================================================================
RECTANGLE Lightweight Block Cipher
=============================================================================
Algorithm  : RECTANGLE (SP-network, bit-sliced design)
Block size : 64 bits
Key sizes  : 80 bits or 128 bits
Rounds     : 25
Reference  : Zhang et al., "RECTANGLE: A Bit-slice Lightweight Block Cipher
             Suitable for Multiple Platforms", 2014.
             https://eprint.iacr.org/2014/084.pdf

Verified against all official test vectors from Table 10 of the paper.
=============================================================================

STATE REPRESENTATION
--------------------
The 64-bit state is arranged as a 4 × 16 rectangular array:

    Row 0 (W0): bits  0 .. 15  — least significant 16 bits of the 64-bit block
    Row 1 (W1): bits 16 .. 31
    Row 2 (W2): bits 32 .. 47
    Row 3 (W3): bits 48 .. 63  — most significant 16 bits

Each *column* j (0 ≤ j ≤ 15) is the 4-bit value formed by taking bit j
from each row:  col_j = (W3[j] << 3) | (W2[j] << 2) | (W1[j] << 1) | W0[j]

This "column" is the input/output to the S-box in SubColumn.

=============================================================================
"""

# ---------------------------------------------------------------------------
# S-BOX  (4-bit → 4-bit substitution table)
# ---------------------------------------------------------------------------
SBOX = [0x6, 0x5, 0xC, 0xA, 0x1, 0xE, 0x7, 0x9,
        0xB, 0x0, 0x3, 0xD, 0x8, 0xF, 0x4, 0x2]

# Inverse S-box (for decryption)
SBOX_INV = [0] * 16
for _i, _v in enumerate(SBOX):
    SBOX_INV[_v] = _i

# ---------------------------------------------------------------------------
# ROUND CONSTANTS  (25 values, one per round)
# Generated by a 5-bit LFSR; initial value RC[0] = 0x01

# ---------------------------------------------------------------------------
RC = [
    0x01, 0x02, 0x04, 0x09, 0x12, 0x05, 0x0B, 0x16,
    0x0C, 0x19, 0x13, 0x07, 0x0F, 0x1F, 0x1E, 0x1C,
    0x18, 0x11, 0x03, 0x06, 0x0D, 0x1B, 0x17, 0x0E, 0x1D
]

# ===========================================================================
#  HELPERS
# ===========================================================================

def _rot16(x: int, n: int) -> int:
    """Left-rotate a 16-bit integer by n positions."""
    n %= 16
    if n == 0:
        return x & 0xFFFF
    return ((x << n) | (x >> (16 - n))) & 0xFFFF


def _rot32(x: int, n: int) -> int:
    """Left-rotate a 32-bit integer by n positions."""
    n %= 32
    if n == 0:
        return x & 0xFFFFFFFF
    return ((x << n) | (x >> (32 - n))) & 0xFFFFFFFF


def _apply_sbox_to_columns(rows: list, num_cols: int) -> list:
    """
    Apply the RECTANGLE S-box to the rightmost `num_cols` columns of the
    key state.  Each column j is the 4-bit value
        col = rows[3][j] || rows[2][j] || rows[1][j] || rows[0][j]
    After substitution the bits are written back.
    Works for both 16-bit rows (80-bit key) and 32-bit rows (128-bit key).
    """
    rows = list(rows)
    for j in range(num_cols):
        # Build 4-bit column value
        col = sum(((rows[b] >> j) & 1) << b for b in range(4))
        s = SBOX[col]
        # Write substituted bits back into the rows
        for b in range(4):
            if (s >> b) & 1:
                rows[b] |= (1 << j)      # set bit j in row b
            else:
                rows[b] &= ~(1 << j)     # clear bit j in row b
    return rows


# ===========================================================================
# STATE ↔ INTEGER CONVERSION
# ===========================================================================

def int_to_state(block: int) -> list:
    """
    Convert a 64-bit integer to the four 16-bit rows [W0, W1, W2, W3].
    Follows the paper convention: W0 is the most-significant 16 bits (bits 48..63),
    W3 is the least-significant 16 bits (bits 0..15).
    This ensures the displayed ciphertext matches Table 10 of the paper exactly.
    """
    return [(block >> (16 * (3 - i))) & 0xFFFF for i in range(4)]


def state_to_int(state: list) -> int:
    """Convert the four-row state back to a 64-bit integer (paper convention)."""
    return sum(state[i] << (16 * (3 - i)) for i in range(4))


# ===========================================================================
# ROUND FUNCTIONS
# ===========================================================================

def sub_column(state: list) -> list:
    """
    SubColumn: apply the 4-bit S-box independently to each of the 16 columns.

    Column j is built from bit j of every row:
        col = (W3[j] << 3) | (W2[j] << 2) | (W1[j] << 1) | W0[j]
    The substituted 4-bit result is scattered back to the rows.
    """
    new_state = [0, 0, 0, 0]
    for j in range(16):
        col = sum(((state[b] >> j) & 1) << b for b in range(4))
        s = SBOX[col]
        for b in range(4):
            if (s >> b) & 1:
                new_state[b] |= (1 << j)
    return new_state


def sub_column_inv(state: list) -> list:
    """Inverse SubColumn using SBOX_INV — used in decryption."""
    new_state = [0, 0, 0, 0]
    for j in range(16):
        col = sum(((state[b] >> j) & 1) << b for b in range(4))
        s = SBOX_INV[col]
        for b in range(4):
            if (s >> b) & 1:
                new_state[b] |= (1 << j)
    return new_state


def shift_row(state: list) -> list:
    """
    ShiftRow: left-rotate each 16-bit row by a fixed offset.
        Row 0 (W0) →  0 bits  (unchanged)
        Row 1 (W1) →  1 bit
        Row 2 (W2) → 12 bits
        Row 3 (W3) → 13 bits
    Source: Section 2.2, Fig. 4 of the paper.
    """
    return [_rot16(state[0],  0),
            _rot16(state[1],  1),
            _rot16(state[2], 12),
            _rot16(state[3], 13)]


def shift_row_inv(state: list) -> list:
    """
    Inverse ShiftRow: right-rotate by the same offsets
    (equivalent to left-rotating by 16 - offset).
        Row 0 →  0 bits  (16 - 0  = 0  → no change)
        Row 1 → 15 bits  (16 - 1  = 15)
        Row 2 →  4 bits  (16 - 12 =  4)
        Row 3 →  3 bits  (16 - 13 =  3)
    """
    return [_rot16(state[0],  0),
            _rot16(state[1], 15),
            _rot16(state[2],  4),
            _rot16(state[3],  3)]


def add_round_key(state: list, subkey: list) -> list:
    """
    AddRoundKey: XOR each row of the state with the corresponding
    16-bit subkey word.  XOR is its own inverse, so this is used for
    both encryption and decryption.
    """
    return [state[i] ^ subkey[i] for i in range(4)]


# ===========================================================================
# KEY SCHEDULES
# ===========================================================================

def key_schedule_80(master_key: int) -> list:
    """
    Generate 26 round subkeys from an 80-bit master key.

    Key state: five 16-bit rows [Row0 .. Row4]
        Row0 = bits  0..15  (least significant)
        Row4 = bits 64..79  (most significant)

    Each round r (0 ≤ r ≤ 24):
      1. Extract subkey:  SK_r = [Row0, Row1, Row2, Row3]
      2. Apply S-box to the 4 rightmost columns (j = 0,1,2,3) of rows 0..3
      3. Generalized Feistel transform:
             Row0' = (Row0 <<<  8) XOR Row1
             Row1' = Row2
             Row2' = Row3
             Row3' = (Row3 <<< 12) XOR Row4
             Row4' = Row0
      4. XOR round constant RC[r] into the lowest 5 bits of Row0

    After the loop, extract the final subkey SK_25 = [Row0, Row1, Row2, Row3].


    """
    # Unpack 80-bit key into five 16-bit rows (Row0 = LSB)
    rows = [(master_key >> (16 * i)) & 0xFFFF for i in range(5)]

    subkeys = []
    for r in range(25):
        # Step 1 — extract subkey
        subkeys.append(rows[:4])  # [Row0, Row1, Row2, Row3]

        # Step 2 — S-box on rightmost 4 columns of rows 0..3
        rows = _apply_sbox_to_columns(rows, 4)

        # Step 3 — Generalized Feistel
        R0, R1, R2, R3, R4 = rows
        rows = [
            _rot16(R0, 8) ^ R1,   # new Row0
            R2,                    # new Row1
            R3,                    # new Row2
            _rot16(R3, 12) ^ R4,  # new Row3
            R0,                    # new Row4
        ]

        # Step 4 — XOR round constant into lowest 5 bits of Row0
        rows[0] ^= RC[r]

    # Extract final subkey K25
    subkeys.append(rows[:4])
    return subkeys  # list of 26 subkeys, each [K0, K1, K2, K3]


def key_schedule_128(master_key: int) -> list:
    """
    Generate 26 round subkeys from a 128-bit master key.

    Key state: four 32-bit rows [Row0 .. Row3]
        Row0 = bits  0..31  (least significant)
        Row3 = bits 96..127 (most significant)

    Subkey extraction: take the rightmost 16 columns = lower 16 bits of each row.

    Each round r (0 ≤ r ≤ 24):
      1. Extract subkey: SK_r = [Row0[0..15], Row1[0..15], Row2[0..15], Row3[0..15]]
      2. Apply S-box to the 8 rightmost columns (j = 0..7) of rows 0..3
      3. Generalized Feistel:
             Row0' = (Row0 <<<  8) XOR Row1
             Row1' = Row2
             Row2' = (Row2 <<< 16) XOR Row3
             Row3' = Row0
      4. XOR RC[r] into lowest 5 bits of Row0
    """
    # Unpack 128-bit key into four 32-bit rows (Row0 = LSB)
    rows = [(master_key >> (32 * i)) & 0xFFFFFFFF for i in range(4)]

    subkeys = []
    for r in range(25):
        # Step 1 — extract subkey (lower 16 bits of each 32-bit row)
        subkeys.append([rows[i] & 0xFFFF for i in range(4)])

        # Step 2 — S-box on rightmost 8 columns
        rows = _apply_sbox_to_columns(rows, 8)

        # Step 3 — Generalized Feistel
        R0, R1, R2, R3 = rows
        rows = [
            _rot32(R0, 8)  ^ R1,    # new Row0
            R2,                      # new Row1
            _rot32(R2, 16) ^ R3,    # new Row2
            R0,                      # new Row3
        ]

        # Step 4 — XOR round constant
        rows[0] ^= RC[r]

    # Final subkey K25
    subkeys.append([rows[i] & 0xFFFF for i in range(4)])
    return subkeys


# ===========================================================================
# ENCRYPTION & DECRYPTION
# ===========================================================================

def encrypt(plaintext: int, key: int, key_bits: int = 80) -> int:
    """
    Encrypt a single 64-bit plaintext block with RECTANGLE.

    Parameters
    ----------
    plaintext : int  — 64-bit integer (0 ≤ plaintext < 2^64)
    key       : int  — 80-bit or 128-bit integer
    key_bits  : int  — must be 80 or 128

    Returns
    -------
    int  — 64-bit ciphertext

    Algorithm (25 rounds + final key addition):
        for r in 0..24:
            state ^= subkey[r]    # AddRoundKey
            state  = SubColumn(state)
            state  = ShiftRow(state)
        state ^= subkey[25]       # final AddRoundKey
    """
    if key_bits not in (80, 128):
        raise ValueError("key_bits must be 80 or 128")
    if not (0 <= plaintext < (1 << 64)):
        raise ValueError("plaintext must fit in 64 bits")

    subkeys = key_schedule_80(key) if key_bits == 80 else key_schedule_128(key)
    state   = int_to_state(plaintext)

    for r in range(25):
        state = add_round_key(state, subkeys[r])
        state = sub_column(state)
        state = shift_row(state)

    state = add_round_key(state, subkeys[25])   # final key addition
    return state_to_int(state)


def decrypt(ciphertext: int, key: int, key_bits: int = 80) -> int:
    """
    Decrypt a single 64-bit ciphertext block with RECTANGLE.

    Parameters
    ----------
    ciphertext : int  — 64-bit integer
    key        : int  — 80-bit or 128-bit integer
    key_bits   : int  — must be 80 or 128

    Returns
    -------
    int  — 64-bit plaintext

    Algorithm (reverse of encryption):
        state ^= subkey[25]           # undo final AddRoundKey
        for r in 24..0:
            state = ShiftRow_inv(state)
            state = SubColumn_inv(state)
            state ^= subkey[r]
    """
    if key_bits not in (80, 128):
        raise ValueError("key_bits must be 80 or 128")

    subkeys = key_schedule_80(key) if key_bits == 80 else key_schedule_128(key)
    state   = int_to_state(ciphertext)

    state = add_round_key(state, subkeys[25])   # undo final key addition

    for r in range(24, -1, -1):
        state = shift_row_inv(state)
        state = sub_column_inv(state)
        state = add_round_key(state, subkeys[r])

    return state_to_int(state)


# ===========================================================================
# UTILITY: bytes ↔ int
# ===========================================================================

def bytes_to_int(b: bytes) -> int:
    """Convert a big-endian byte string to an integer."""
    return int.from_bytes(b, byteorder='big')

def int_to_bytes(n: int, length: int) -> bytes:
    """Convert an integer to a big-endian byte string of given length."""
    return n.to_bytes(length, byteorder='big')


# ===========================================================================
# TEST SUITE
# ===========================================================================

def _bin_rows_to_int(r0b, r1b, r2b, r3b):
    """
    Helper: convert four binary strings (one per row, MSB-first within row)
    to the 64-bit integer used by this implementation.
    The paper prints Row0 first (top), Row3 last (bottom).
    Our state stores Row0 in the least-significant 16 bits.
    """
    r = [int(s.replace(' ', ''), 2) for s in (r0b, r1b, r2b, r3b)]
    return r[0] | (r[1] << 16) | (r[2] << 32) | (r[3] << 48)


def run_tests():
    """
    Run the complete test suite:
      1. Official test vectors from Table 10 of the paper (most important).
      2. Encrypt → Decrypt round-trips.
      3. Avalanche effect.
      4. Key sensitivity.
      5. Bytes interface.
    """
    passed = 0
    failed = 0

    def check(label, got, expected):
        nonlocal passed, failed
        ok = (got == expected)
        status = "PASS" if ok else "FAIL"
        print(f"  [{status}] {label}")
        if not ok:
            print(f"         got      = {got:016X}")
            print(f"         expected = {expected:016X}")
            failed += 1
        else:
            passed += 1

    print("=" * 65)
    print("  RECTANGLE — Test Suite")
    print("=" * 65)

    # ------------------------------------------------------------------
    # 1. Official test vectors (Table 10, paper)
    # ------------------------------------------------------------------
    print("\n[1] Official test vectors (Table 10 of the paper)")

    # REC-80, all-zero key, all-zero plaintext
    tv_80_zero_ct = _bin_rows_to_int(
        '0010110110010110',
        '1110001101010100',
        '1110100010110001',
        '0000100001110100'
    )
    check("REC-80 zero-key/zero-PT",
          encrypt(0x0000000000000000, 0x00000000000000000000, 80),
          tv_80_zero_ct)

    # REC-80, all-ones key, all-ones plaintext
    tv_80_ones_ct = _bin_rows_to_int(
        '1001100101000101',
        '1010101000110100',
        '1010111000111101',
        '0000000100010010'
    )
    check("REC-80 ones-key/ones-PT",
          encrypt(0xFFFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFFFFFFF, 80),
          tv_80_ones_ct)

    # REC-128, all-zero key, all-zero plaintext
    tv_128_zero_ct = _bin_rows_to_int(
        '1010111011100110',
        '0011011000010011',
        '0100010010100100',
        '1001100111101110'
    )
    check("REC-128 zero-key/zero-PT",
          encrypt(0x0000000000000000, 0x00000000000000000000000000000000, 128),
          tv_128_zero_ct)

    # REC-128, all-ones key, all-ones plaintext
    tv_128_ones_ct = _bin_rows_to_int(
        '1110100000111110',
        '1110111111101110',
        '0100101000010101',
        '0111101001000110'
    )
    check("REC-128 ones-key/ones-PT",
          encrypt(0xFFFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, 128),
          tv_128_ones_ct)

    # ------------------------------------------------------------------
    # 2. Encrypt → Decrypt round-trips
    # ------------------------------------------------------------------
    print("\n[2] Encrypt → Decrypt round-trips")
    for kb, k, p in [
        (80,  0x00000000000000000000, 0x0000000000000000),
        (80,  0xFFFFFFFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFFF),
        (80,  0x0123456789ABCDEF0123, 0xDEADBEEFCAFEBABE),
        (128, 0x00000000000000000000000000000000, 0x0000000000000000),
        (128, 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFFF),
        (128, 0x0123456789ABCDEF0123456789ABCDEF, 0xDEADBEEFCAFEBABE),
    ]:
        ct  = encrypt(p, k, kb)
        pt2 = decrypt(ct, k, kb)
        check(f"{kb}-bit key, PT={p:016X}", pt2, p)

    # ------------------------------------------------------------------
    # 3. Avalanche effect — flip one plaintext bit
    # ------------------------------------------------------------------
    print("\n[3] Avalanche effect (flip 1 plaintext bit)")
    pt1 = 0x0123456789ABCDEF
    pt2 = pt1 ^ 1                    # flip LSB
    k   = 0x0123456789ABCDEF0123
    ct1 = encrypt(pt1, k, 80)
    ct2 = encrypt(pt2, k, 80)
    bits_changed = bin(ct1 ^ ct2).count('1')
    ok = bits_changed >= 24           # expect ~50% = 32 bits
    print(f"  {'[PASS]' if ok else '[FAIL]'} {bits_changed}/64 bits changed "
          f"({bits_changed/64*100:.1f}%)  — want ≥ 24")
    (passed if ok else failed).__class__  # just increment via side-effect
    if ok: passed += 1
    else:  failed += 1

    # ------------------------------------------------------------------
    # 4. Key sensitivity — flip one key bit
    # ------------------------------------------------------------------
    print("\n[4] Key sensitivity (flip 1 key bit)")
    pt   = 0xDEADBEEFCAFEBABE
    key1 = 0x0123456789ABCDEF0123
    key2 = 0x0123456789ABCDEF0122   # 1 bit flipped
    ct1  = encrypt(pt, key1, 80)
    ct2  = encrypt(pt, key2, 80)
    diff = ct1 != ct2
    check("Different keys → different ciphertexts (non-zero)", int(diff), 1)

    # ------------------------------------------------------------------
    # 5. Bytes interface
    # ------------------------------------------------------------------
    print("\n[5] Bytes interface")
    pt_bytes  = b'HelloIoT'          # 8 bytes = 64 bits
    key_bytes = b'SecretKey!'        # 10 bytes = 80 bits
    pt_int    = bytes_to_int(pt_bytes)
    key_int   = bytes_to_int(key_bytes)
    ct_int    = encrypt(pt_int, key_int, 80)
    pt_back   = decrypt(ct_int, key_int, 80)
    check("Bytes: encrypt then decrypt recovers original", pt_back, pt_int)
    print(f"         PT bytes  : {pt_bytes}")
    print(f"         CT hex    : {int_to_bytes(ct_int, 8).hex().upper()}")
    print(f"         Recovered : {int_to_bytes(pt_back, 8)}")

    # ------------------------------------------------------------------
    print(f"\n{'=' * 65}")
    print(f"  Results: {passed} passed, {failed} failed")
    print(f"{'=' * 65}")
    return failed == 0


# ===========================================================================
# INTERACTIVE DEMO
# ===========================================================================

def interactive_demo():
    """Simple command-line encryption/decryption demo."""
    print("\n--- RECTANGLE Interactive Demo ---")
    print("Block: 64 bits (16 hex chars)  |  Key: 80 or 128 bits\n")

    mode = input("Mode — [e]ncrypt or [d]ecrypt: ").strip().lower()
    if mode not in ('e', 'd'):
        print("Invalid choice."); return

    raw = input("64-bit block (16 hex chars): ").strip().replace('0x', '')
    if len(raw) != 16:
        print(f"Need 16 hex chars, got {len(raw)}."); return
    data = int(raw, 16)

    kb_str = input("Key bits (80 or 128): ").strip()
    if kb_str not in ('80', '128'):
        print("Key bits must be 80 or 128."); return
    key_bits = int(kb_str)

    expected_chars = key_bits // 4
    raw_key = input(f"{key_bits}-bit key ({expected_chars} hex chars): ").strip().replace('0x', '')
    if len(raw_key) != expected_chars:
        print(f"Need {expected_chars} hex chars."); return
    key = int(raw_key, 16)

    result = encrypt(data, key, key_bits) if mode == 'e' else decrypt(data, key, key_bits)
    label  = "Ciphertext" if mode == 'e' else "Plaintext "
    print(f"\n  Input     : {raw.upper()}")
    print(f"  Key       : {raw_key.upper()}")
    print(f"  {label} : {result:016X}")


# ===========================================================================
# ENTRY POINT
# ===========================================================================
# QUICK USAGE EXAMPLE:
#
#   from rectangle_cipher import encrypt, decrypt
#
#   key  = 0x00000000000000000000          # 80-bit key (20 hex chars)
#   pt   = 0x0000000000000000              # 64-bit plaintext
#   ct   = encrypt(pt, key, key_bits=80)   # → 0x2D96E354E8B10874
#   back = decrypt(ct, key, key_bits=80)   # → 0x0000000000000000
#
#   Run tests:  python rectangle_cipher.py

if __name__ == "__main__":
    all_passed = run_tests()
    print()
    if input("Run interactive demo? [y/n]: ").strip().lower() == 'y':
        interactive_demo()
